### PR TITLE
release ws-biblio-ref@1.1.0

### PR DESCRIPTION
**Pull request by leogail**
Forgot to make a version

### CODE REVIEW

**Comment by parmentf** [comment]
OK, it did not build (nor push) the docker image, because you did not push the tag.

```bash
git push --tags
```

That means you did not use the `npm -w services/biblio-ref version minor` way?

**Comment by leogail** [comment]
First time, i saw you did a version 1.0.1 ; i though it was my new version so i didnt create one ; but it looks like it wasn't the newest version, that's why i created this PR

But if you talk about this version (1.1) :
I used the correct way. It failed beceause there wasn't distant remote.
So i created it and used "git push" but not git push --tags .

**Review by parmentf — CHANGES_REQUESTED** [review]
Yep, now you only need to push the tag :+1:

**Comment by leogail** [comment]
forgot to push the tags..

**Review by parmentf — APPROVED** [review]

**Pull request merged**
