### PR TITLE
[data-workflow] avoid having json in csv

### PR DESCRIPTION
**Pull request by touv**

### CODE REVIEW

**Comment by parmentf** [comment]
Is it a change to apply to `data-computer` and other `data-*` services?

**Review by parmentf — APPROVED** [review]
It would be better with a test...

**Comment by touv** [comment]
> Is it a change to apply to `data-computer` and other `data-*` services?

maybe everywhere, but initially it's to offer better CSV output with bibCheck in iafactory

**Comment by touv** [comment]
> It would be better with a test...

you're right, but currently there were no tests for bibcheck

so maybe I could add one for tag-cloud-*

**Pull request merged**
